/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Airports entity stored in table airports.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="airports", catalog="flight_booking" )
public class Airports implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="airport_code", nullable=false)
    private Integer airportCode ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="airport_name", length=255)
    private String airportName ;     @Column(name="airport_location", length=255)
    private String airportLocation ;     @Column(name="other_details", length=255)
    private String otherDetails ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Airports() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setAirportCode(Integer airportCode) {
        this.airportCode = airportCode ;
    }
	public Integer getAirportCode() {
        return this.airportCode;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : airport_name (VARCHAR) 
	public void setAirportName(String airportName) {this.airportName = airportName;}
	public String getAirportName() {return this.airportName;}

	//--- DATABASE MAPPING : airport_location (VARCHAR) 
	public void setAirportLocation(String airportLocation) {this.airportLocation = airportLocation;}
	public String getAirportLocation() {return this.airportLocation;}

	//--- DATABASE MAPPING : other_details (VARCHAR) 
	public void setOtherDetails(String otherDetails) {this.otherDetails = otherDetails;}
	public String getOtherDetails() {return this.otherDetails;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(airportCode); 
		sb.append(airportName); 
		sb.append("|"); 
		sb.append(airportLocation); 
		sb.append("|"); 
		sb.append(otherDetails); 
        return sb.toString();
    }
}