/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for BookingAgents entity stored in table booking_agents.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="booking_agents", catalog="flight_booking" )
public class BookingAgents implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="agent_id", nullable=false)
    private Integer agentId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="agent_name", length=225)
    private String agentName ;     @Column(name="agent_details", length=255)
    private String agentDetails ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BookingAgents() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setAgentId(Integer agentId) {
        this.agentId = agentId ;
    }
	public Integer getAgentId() {
        return this.agentId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : agent_name (VARCHAR) 
	public void setAgentName(String agentName) {this.agentName = agentName;}
	public String getAgentName() {return this.agentName;}

	//--- DATABASE MAPPING : agent_details (VARCHAR) 
	public void setAgentDetails(String agentDetails) {this.agentDetails = agentDetails;}
	public String getAgentDetails() {return this.agentDetails;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(agentId); 
		sb.append(agentName); 
		sb.append("|"); 
		sb.append(agentDetails); 
        return sb.toString();
    }
}