/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for FlightSchedules entity stored in table flight_schedules.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="flight_schedules", catalog="flight_booking" )
public class FlightSchedules implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="flight_number", nullable=false)
    private Integer flightNumber ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="airline_code")
    private Integer airlineCode ; // Foreign Key     @Column(name="usual_aircraft_type_code")
    private Integer usualAircraftTypeCode ;     @Column(name="origin_airport_code")
    private Integer originAirportCode ;     @Column(name="destination_airport_code")
    private Integer destinationAirportCode ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="departure_date_time")
    private Date departureDateTime ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="arrival_date_time")
    private Date arrivalDateTime ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FlightSchedules() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setFlightNumber(Integer flightNumber) {
        this.flightNumber = flightNumber ;
    }
	public Integer getFlightNumber() {
        return this.flightNumber;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : airline_code (INT) 
	public void setAirlineCode(Integer airlineCode) {this.airlineCode = airlineCode;}
	public Integer getAirlineCode() {return this.airlineCode;}

	//--- DATABASE MAPPING : usual_aircraft_type_code (INT) 
	public void setUsualAircraftTypeCode(Integer usualAircraftTypeCode) {this.usualAircraftTypeCode = usualAircraftTypeCode;}
	public Integer getUsualAircraftTypeCode() {return this.usualAircraftTypeCode;}

	//--- DATABASE MAPPING : origin_airport_code (INT) 
	public void setOriginAirportCode(Integer originAirportCode) {this.originAirportCode = originAirportCode;}
	public Integer getOriginAirportCode() {return this.originAirportCode;}

	//--- DATABASE MAPPING : destination_airport_code (INT) 
	public void setDestinationAirportCode(Integer destinationAirportCode) {this.destinationAirportCode = destinationAirportCode;}
	public Integer getDestinationAirportCode() {return this.destinationAirportCode;}

	//--- DATABASE MAPPING : departure_date_time (DATETIME) 
	public void setDepartureDateTime(Date departureDateTime) {this.departureDateTime = departureDateTime;}
	public Date getDepartureDateTime() {return this.departureDateTime;}

	//--- DATABASE MAPPING : arrival_date_time (DATETIME) 
	public void setArrivalDateTime(Date arrivalDateTime) {this.arrivalDateTime = arrivalDateTime;}
	public Date getArrivalDateTime() {return this.arrivalDateTime;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(flightNumber); 
		sb.append(airlineCode); 
		sb.append("|"); 
		sb.append(usualAircraftTypeCode); 
		sb.append("|"); 
		sb.append(originAirportCode); 
		sb.append("|"); 
		sb.append(destinationAirportCode); 
		sb.append("|"); 
		sb.append(departureDateTime); 
		sb.append("|"); 
		sb.append(arrivalDateTime); 
        return sb.toString();
    }
}