/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for Legs entity stored in table legs.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="legs", catalog="flight_booking" )
public class Legs implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="leg_id", nullable=false)
    private Integer legId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="flight_number")
    private Integer flightNumber ; // Foreign Key     @Column(name="origin_airport_code")
    private Integer originAirportCode ; // Foreign Key     @Column(name="destination_airport_code")
    private Integer destinationAirportCode ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actual_departure_time")
    private Date actualDepartureTime ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actual_arrival_time")
    private Date actualArrivalTime ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Legs() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setLegId(Integer legId) {
        this.legId = legId ;
    }
	public Integer getLegId() {
        return this.legId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : flight_number (INT) 
	public void setFlightNumber(Integer flightNumber) {this.flightNumber = flightNumber;}
	public Integer getFlightNumber() {return this.flightNumber;}

	//--- DATABASE MAPPING : origin_airport_code (INT) 
	public void setOriginAirportCode(Integer originAirportCode) {this.originAirportCode = originAirportCode;}
	public Integer getOriginAirportCode() {return this.originAirportCode;}

	//--- DATABASE MAPPING : destination_airport_code (INT) 
	public void setDestinationAirportCode(Integer destinationAirportCode) {this.destinationAirportCode = destinationAirportCode;}
	public Integer getDestinationAirportCode() {return this.destinationAirportCode;}

	//--- DATABASE MAPPING : actual_departure_time (DATETIME) 
	public void setActualDepartureTime(Date actualDepartureTime) {this.actualDepartureTime = actualDepartureTime;}
	public Date getActualDepartureTime() {return this.actualDepartureTime;}

	//--- DATABASE MAPPING : actual_arrival_time (DATETIME) 
	public void setActualArrivalTime(Date actualArrivalTime) {this.actualArrivalTime = actualArrivalTime;}
	public Date getActualArrivalTime() {return this.actualArrivalTime;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(legId); 
		sb.append(flightNumber); 
		sb.append("|"); 
		sb.append(originAirportCode); 
		sb.append("|"); 
		sb.append(destinationAirportCode); 
		sb.append("|"); 
		sb.append(actualDepartureTime); 
		sb.append("|"); 
		sb.append(actualArrivalTime); 
        return sb.toString();
    }
}