/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for LtineraryReservations entity stored in table ltinerary_reservations.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="ltinerary_reservations", catalog="flight_booking" )
public class LtineraryReservations implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="reservation_id", nullable=false)
    private Integer reservationId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="agent_id", nullable=false)
    private Integer agentId ; // Foreign Key     @Column(name="passenger_id", nullable=false)
    private Integer passengerId ; // Foreign Key     @Column(name="reservatiion_status_code")
    private Integer reservatiionStatusCode ;     @Column(name="ticket_type_code")
    private Integer ticketTypeCode ;     @Column(name="travel_class_code")
    private Integer travelClassCode ;     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_reservation_made")
    private Date dateReservationMade ;     @Column(name="number_in_party")
    private Integer numberInParty ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public LtineraryReservations() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId ;
    }
	public Integer getReservationId() {
        return this.reservationId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : agent_id (INT) 
	public void setAgentId(Integer agentId) {this.agentId = agentId;}
	public Integer getAgentId() {return this.agentId;}

	//--- DATABASE MAPPING : passenger_id (INT) 
	public void setPassengerId(Integer passengerId) {this.passengerId = passengerId;}
	public Integer getPassengerId() {return this.passengerId;}

	//--- DATABASE MAPPING : reservatiion_status_code (INT) 
	public void setReservatiionStatusCode(Integer reservatiionStatusCode) {this.reservatiionStatusCode = reservatiionStatusCode;}
	public Integer getReservatiionStatusCode() {return this.reservatiionStatusCode;}

	//--- DATABASE MAPPING : ticket_type_code (INT) 
	public void setTicketTypeCode(Integer ticketTypeCode) {this.ticketTypeCode = ticketTypeCode;}
	public Integer getTicketTypeCode() {return this.ticketTypeCode;}

	//--- DATABASE MAPPING : travel_class_code (INT) 
	public void setTravelClassCode(Integer travelClassCode) {this.travelClassCode = travelClassCode;}
	public Integer getTravelClassCode() {return this.travelClassCode;}

	//--- DATABASE MAPPING : date_reservation_made (DATETIME) 
	public void setDateReservationMade(Date dateReservationMade) {this.dateReservationMade = dateReservationMade;}
	public Date getDateReservationMade() {return this.dateReservationMade;}

	//--- DATABASE MAPPING : number_in_party (INT) 
	public void setNumberInParty(Integer numberInParty) {this.numberInParty = numberInParty;}
	public Integer getNumberInParty() {return this.numberInParty;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(reservationId); 
		sb.append(agentId); 
		sb.append("|"); 
		sb.append(passengerId); 
		sb.append("|"); 
		sb.append(reservatiionStatusCode); 
		sb.append("|"); 
		sb.append(ticketTypeCode); 
		sb.append("|"); 
		sb.append(travelClassCode); 
		sb.append("|"); 
		sb.append(dateReservationMade); 
		sb.append("|"); 
		sb.append(numberInParty); 
        return sb.toString();
    }
}