/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;


import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for LtineraryLegs entity stored in table ltinerary_legs.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="ltinerary_legs", catalog="flight_booking" )
public class LtineraryLegs implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private LtineraryLegsKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public LtineraryLegs() {
		super();
		this.compositePrimaryKey = new LtineraryLegsKey();       
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setReservationId(Integer reservationId) {
        this.compositePrimaryKey.setReservationId(reservationId) ;
    }
	public Integer getReservationId() {
        return this.compositePrimaryKey.getReservationId() ;
    }
	public void setLegId(Integer legId) {
        this.compositePrimaryKey.setLegId(legId) ;
    }
	public Integer getLegId() {
        return this.compositePrimaryKey.getLegId() ;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("[" + compositePrimaryKey + "]"); 
        return sb.toString();
    }
}