/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Passengers entity stored in table passengers.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="passengers", catalog="flight_booking" )
public class Passengers implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="passenger_id", nullable=false)
    private Integer passengerId ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="first_name", length=255)
    private String firstName ;     @Column(name="second_name", length=255)
    private String secondName ;     @Column(name="last_name", length=255)
    private String lastName ;     @Column(name="phone_number")
    private Integer phoneNumber ;     @Column(name="email_address", length=255)
    private String emailAddress ;     @Column(name="address_lines", length=255)
    private String addressLines ;     @Column(name="city", length=255)
    private String city ;     @Column(name="stat_province_country", length=255)
    private String statProvinceCountry ;     @Column(name="country", length=255)
    private String country ;     @Column(name="other_passenger_details", length=255)
    private String otherPassengerDetails ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Passengers() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setPassengerId(Integer passengerId) {
        this.passengerId = passengerId ;
    }
	public Integer getPassengerId() {
        return this.passengerId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : first_name (VARCHAR) 
	public void setFirstName(String firstName) {this.firstName = firstName;}
	public String getFirstName() {return this.firstName;}

	//--- DATABASE MAPPING : second_name (VARCHAR) 
	public void setSecondName(String secondName) {this.secondName = secondName;}
	public String getSecondName() {return this.secondName;}

	//--- DATABASE MAPPING : last_name (VARCHAR) 
	public void setLastName(String lastName) {this.lastName = lastName;}
	public String getLastName() {return this.lastName;}

	//--- DATABASE MAPPING : phone_number (INT) 
	public void setPhoneNumber(Integer phoneNumber) {this.phoneNumber = phoneNumber;}
	public Integer getPhoneNumber() {return this.phoneNumber;}

	//--- DATABASE MAPPING : email_address (VARCHAR) 
	public void setEmailAddress(String emailAddress) {this.emailAddress = emailAddress;}
	public String getEmailAddress() {return this.emailAddress;}

	//--- DATABASE MAPPING : address_lines (VARCHAR) 
	public void setAddressLines(String addressLines) {this.addressLines = addressLines;}
	public String getAddressLines() {return this.addressLines;}

	//--- DATABASE MAPPING : city (VARCHAR) 
	public void setCity(String city) {this.city = city;}
	public String getCity() {return this.city;}

	//--- DATABASE MAPPING : stat_province_country (VARCHAR) 
	public void setStatProvinceCountry(String statProvinceCountry) {this.statProvinceCountry = statProvinceCountry;}
	public String getStatProvinceCountry() {return this.statProvinceCountry;}

	//--- DATABASE MAPPING : country (VARCHAR) 
	public void setCountry(String country) {this.country = country;}
	public String getCountry() {return this.country;}

	//--- DATABASE MAPPING : other_passenger_details (VARCHAR) 
	public void setOtherPassengerDetails(String otherPassengerDetails) {this.otherPassengerDetails = otherPassengerDetails;}
	public String getOtherPassengerDetails() {return this.otherPassengerDetails;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(passengerId); 
		sb.append(firstName); 
		sb.append("|"); 
		sb.append(secondName); 
		sb.append("|"); 
		sb.append(lastName); 
		sb.append("|"); 
		sb.append(phoneNumber); 
		sb.append("|"); 
		sb.append(emailAddress); 
		sb.append("|"); 
		sb.append(addressLines); 
		sb.append("|"); 
		sb.append(city); 
		sb.append("|"); 
		sb.append(statProvinceCountry); 
		sb.append("|"); 
		sb.append(country); 
		sb.append("|"); 
		sb.append(otherPassengerDetails); 
        return sb.toString();
    }
}