/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for RefCalendar entity stored in table ref_calendar.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="ref_calendar", catalog="flight_booking" )
public class RefCalendar implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="day_date", nullable=false)
    private Date dayDate ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="day_number")
    private Integer dayNumber ;     @Column(name="business_day_yn", length=255)
    private String businessDayYn ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RefCalendar() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setDayDate(Date dayDate) {
        this.dayDate = dayDate ;
    }
	public Date getDayDate() {
        return this.dayDate;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : day_number (INT) 
	public void setDayNumber(Integer dayNumber) {this.dayNumber = dayNumber;}
	public Integer getDayNumber() {return this.dayNumber;}

	//--- DATABASE MAPPING : business_day_yn (VARCHAR) 
	public void setBusinessDayYn(String businessDayYn) {this.businessDayYn = businessDayYn;}
	public String getBusinessDayYn() {return this.businessDayYn;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(dayDate); 
		sb.append(dayNumber); 
		sb.append("|"); 
		sb.append(businessDayYn); 
        return sb.toString();
    }
}