/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;


import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for ReservationPayments entity stored in table reservation_payments.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="reservation_payments", catalog="flight_booking" )
public class ReservationPayments implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private ReservationPaymentsKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ReservationPayments() {
		super();
		this.compositePrimaryKey = new ReservationPaymentsKey();       
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setReservationId(Integer reservationId) {
        this.compositePrimaryKey.setReservationId(reservationId) ;
    }
	public Integer getReservationId() {
        return this.compositePrimaryKey.getReservationId() ;
    }
	public void setPaymentId(Integer paymentId) {
        this.compositePrimaryKey.setPaymentId(paymentId) ;
    }
	public Integer getPaymentId() {
        return this.compositePrimaryKey.getPaymentId() ;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("[" + compositePrimaryKey + "]"); 
        return sb.toString();
    }
}