/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Composite primary key for entity "ReservationPayments" ( stored in table "reservation_payments" )
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
 @Embeddable
public class ReservationPaymentsKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="reservation_id", nullable=false)
    private Integer reservationId ;
    @Column(name="payment_id", nullable=false)
    private Integer paymentId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ReservationPaymentsKey() {
        super();
    }

    public ReservationPaymentsKey(Integer reservationId, Integer paymentId) {
        super();
        this.reservationId = reservationId ;
        this.paymentId = paymentId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
	public void setReservationId(Integer value) {
        this.reservationId = value;
    }
	public Integer getReservationId() {
        return this.reservationId;
    }

	public void setPaymentId(Integer value) {
        this.paymentId = value;
    }
	public Integer getPaymentId() {
        return this.paymentId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(reservationId); 
		sb.append("|"); 
		sb.append(paymentId); 
        return sb.toString();
    }
}
