/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Airports;
import java.util.List;

public interface AirportsService {

	public Airports getOne(Integer airportCode);

	public List<Airports> findAll();

	public Boolean delete(Integer airportCode);

	public Airports create(Airports airports);

	public Airports update(Airports airports);

	public Boolean exist(Airports airports);
}
