/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Airports;
import com.ifi.repository.AirportsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class AirportsServiceImpl implements AirportsService {

	@Autowired
	private AirportsRepository airportsRepository;

	@Override
	public Airports getOne(Integer airportCode) {
		return airportsRepository.getOne(airportCode);
	}

	@Override
	public Boolean delete(Integer airportCode) {
		if (airportsRepository.getOne(airportCode) != null) {
			airportsRepository.deleteById(airportCode);
			return true;
		}
		return false;
	}

	@Override
	public Airports create(Airports airports) {
		return airportsRepository.save(airports);
	}

	@Override
	public Airports update(Airports airportsToUpdate) {
						Airports airports = airportsRepository.getOne(airportsToUpdate.getAirportCode());
																		
				if(airportsToUpdate.getAirportName() !=null) {
			
		}
				if(airportsToUpdate.getAirportLocation() !=null) {
			
		}
				if(airportsToUpdate.getOtherDetails() !=null) {
			
		}
				return airportsRepository.save(airports);
	}

	@Override
	public Boolean exist(Airports airports) {
						return airportsRepository.existsById(airports.getAirportCode());
																	}

	@Override
	public List<Airports> findAll() {
		return airportsRepository.findAll();
	}

}
