/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.BookingAgents;
import com.ifi.repository.BookingAgentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class BookingAgentsServiceImpl implements BookingAgentsService {

	@Autowired
	private BookingAgentsRepository bookingAgentsRepository;

	@Override
	public BookingAgents getOne(Integer agentId) {
		return bookingAgentsRepository.getOne(agentId);
	}

	@Override
	public Boolean delete(Integer agentId) {
		if (bookingAgentsRepository.getOne(agentId) != null) {
			bookingAgentsRepository.deleteById(agentId);
			return true;
		}
		return false;
	}

	@Override
	public BookingAgents create(BookingAgents bookingAgents) {
		return bookingAgentsRepository.save(bookingAgents);
	}

	@Override
	public BookingAgents update(BookingAgents bookingAgentsToUpdate) {
						BookingAgents bookingAgents = bookingAgentsRepository.getOne(bookingAgentsToUpdate.getAgentId());
														
				if(bookingAgentsToUpdate.getAgentName() !=null) {
			
		}
				if(bookingAgentsToUpdate.getAgentDetails() !=null) {
			
		}
				return bookingAgentsRepository.save(bookingAgents);
	}

	@Override
	public Boolean exist(BookingAgents bookingAgents) {
						return bookingAgentsRepository.existsById(bookingAgents.getAgentId());
													}

	@Override
	public List<BookingAgents> findAll() {
		return bookingAgentsRepository.findAll();
	}

}
