/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;


import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.FlightCosts;
import com.ifi.repository.FlightCostsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class FlightCostsServiceImpl implements FlightCostsService {

	@Autowired
	private FlightCostsRepository flightCostsRepository;

	@Override
	public FlightCosts getOne(Integer flightNumber) {
		return flightCostsRepository.getOne(flightNumber);
	}

	@Override
	public Boolean delete(Integer flightNumber) {
		if (flightCostsRepository.getOne(flightNumber) != null) {
			flightCostsRepository.deleteById(flightNumber);
			return true;
		}
		return false;
	}

	@Override
	public FlightCosts create(FlightCosts flightCosts) {
		return flightCostsRepository.save(flightCosts);
	}

	@Override
	public FlightCosts update(FlightCosts flightCostsToUpdate) {
						FlightCosts flightCosts = flightCostsRepository.getOne(flightCostsToUpdate.getFlightNumber());
																						
				if(flightCostsToUpdate.getAircraftTypeCode() !=null) {
			
		}
				if(flightCostsToUpdate.getValidFromDate() !=null) {
			
		}
				if(flightCostsToUpdate.getValidToDate() !=null) {
			
		}
				if(flightCostsToUpdate.getFlightCost() !=null) {
			
		}
				return flightCostsRepository.save(flightCosts);
	}

	@Override
	public Boolean exist(FlightCosts flightCosts) {
						return flightCostsRepository.existsById(flightCosts.getFlightNumber());
																					}

	@Override
	public List<FlightCosts> findAll() {
		return flightCostsRepository.findAll();
	}

}
