/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.FlightCosts;
import java.util.List;

public interface FlightCostsService {

	public FlightCosts getOne(Integer flightNumber);

	public List<FlightCosts> findAll();

	public Boolean delete(Integer flightNumber);

	public FlightCosts create(FlightCosts flightCosts);

	public FlightCosts update(FlightCosts flightCosts);

	public Boolean exist(FlightCosts flightCosts);
}
