/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;


import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.FlightSchedules;
import com.ifi.repository.FlightSchedulesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class FlightSchedulesServiceImpl implements FlightSchedulesService {

	@Autowired
	private FlightSchedulesRepository flightSchedulesRepository;

	@Override
	public FlightSchedules getOne(Integer flightNumber) {
		return flightSchedulesRepository.getOne(flightNumber);
	}

	@Override
	public Boolean delete(Integer flightNumber) {
		if (flightSchedulesRepository.getOne(flightNumber) != null) {
			flightSchedulesRepository.deleteById(flightNumber);
			return true;
		}
		return false;
	}

	@Override
	public FlightSchedules create(FlightSchedules flightSchedules) {
		return flightSchedulesRepository.save(flightSchedules);
	}

	@Override
	public FlightSchedules update(FlightSchedules flightSchedulesToUpdate) {
						FlightSchedules flightSchedules = flightSchedulesRepository.getOne(flightSchedulesToUpdate.getFlightNumber());
																														
				if(flightSchedulesToUpdate.getAirlineCode() !=null) {
			
		}
				if(flightSchedulesToUpdate.getUsualAircraftTypeCode() !=null) {
			
		}
				if(flightSchedulesToUpdate.getOriginAirportCode() !=null) {
			
		}
				if(flightSchedulesToUpdate.getDestinationAirportCode() !=null) {
			
		}
				if(flightSchedulesToUpdate.getDepartureDateTime() !=null) {
			
		}
				if(flightSchedulesToUpdate.getArrivalDateTime() !=null) {
			
		}
				return flightSchedulesRepository.save(flightSchedules);
	}

	@Override
	public Boolean exist(FlightSchedules flightSchedules) {
						return flightSchedulesRepository.existsById(flightSchedules.getFlightNumber());
																													}

	@Override
	public List<FlightSchedules> findAll() {
		return flightSchedulesRepository.findAll();
	}

}
