/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;


import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Legs;
import com.ifi.repository.LegsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class LegsServiceImpl implements LegsService {

	@Autowired
	private LegsRepository legsRepository;

	@Override
	public Legs getOne(Integer legId) {
		return legsRepository.getOne(legId);
	}

	@Override
	public Boolean delete(Integer legId) {
		if (legsRepository.getOne(legId) != null) {
			legsRepository.deleteById(legId);
			return true;
		}
		return false;
	}

	@Override
	public Legs create(Legs legs) {
		return legsRepository.save(legs);
	}

	@Override
	public Legs update(Legs legsToUpdate) {
						Legs legs = legsRepository.getOne(legsToUpdate.getLegId());
																										
				if(legsToUpdate.getFlightNumber() !=null) {
			
		}
				if(legsToUpdate.getOriginAirportCode() !=null) {
			
		}
				if(legsToUpdate.getDestinationAirportCode() !=null) {
			
		}
				if(legsToUpdate.getActualDepartureTime() !=null) {
			
		}
				if(legsToUpdate.getActualArrivalTime() !=null) {
			
		}
				return legsRepository.save(legs);
	}

	@Override
	public Boolean exist(Legs legs) {
						return legsRepository.existsById(legs.getLegId());
																									}

	@Override
	public List<Legs> findAll() {
		return legsRepository.findAll();
	}

}
