/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.LtineraryReservations;
import java.util.List;

public interface LtineraryReservationsService {

	public LtineraryReservations getOne(Integer reservationId);

	public List<LtineraryReservations> findAll();

	public Boolean delete(Integer reservationId);

	public LtineraryReservations create(LtineraryReservations ltineraryReservations);

	public LtineraryReservations update(LtineraryReservations ltineraryReservations);

	public Boolean exist(LtineraryReservations ltineraryReservations);
}
