/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.LtineraryLegs;
import java.util.List;

public interface LtineraryLegsService {

	public LtineraryLegs getOne(Integer reservationId, Integer legId);

	public List<LtineraryLegs> findAll();

	public Boolean delete(Integer reservationId, Integer legId);

	public LtineraryLegs create(LtineraryLegs ltineraryLegs);

	public LtineraryLegs update(LtineraryLegs ltineraryLegs);

	public Boolean exist(LtineraryLegs ltineraryLegs);
}
