/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;


import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ifi.entity.LtineraryLegs;
import com.ifi.repository.LtineraryLegsRepository;

@Service
@Transactional
public class LtineraryLegsServiceImpl implements LtineraryLegsService {

	@Autowired
	private LtineraryLegsRepository ltineraryLegsRepository;

	@Override
	public LtineraryLegs create(LtineraryLegs ltineraryLegs) {
		return ltineraryLegsRepository.save(ltineraryLegs);
	}

	@Override
	public List<LtineraryLegs> findAll() {
		return ltineraryLegsRepository.findAll();
	}

	@Override
	public LtineraryLegs getOne(Integer reservationId, Integer legId) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Boolean delete(Integer reservationId, Integer legId) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public LtineraryLegs update(LtineraryLegs ltineraryLegs) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Boolean exist(LtineraryLegs ltineraryLegs) {
		// TODO Auto-generated method stub
		return null;
	}

}
