/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Passengers;
import com.ifi.repository.PassengersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class PassengersServiceImpl implements PassengersService {

	@Autowired
	private PassengersRepository passengersRepository;

	@Override
	public Passengers getOne(Integer passengerId) {
		return passengersRepository.getOne(passengerId);
	}

	@Override
	public Boolean delete(Integer passengerId) {
		if (passengersRepository.getOne(passengerId) != null) {
			passengersRepository.deleteById(passengerId);
			return true;
		}
		return false;
	}

	@Override
	public Passengers create(Passengers passengers) {
		return passengersRepository.save(passengers);
	}

	@Override
	public Passengers update(Passengers passengersToUpdate) {
						Passengers passengers = passengersRepository.getOne(passengersToUpdate.getPassengerId());
																																														
				if(passengersToUpdate.getFirstName() !=null) {
			
		}
				if(passengersToUpdate.getSecondName() !=null) {
			
		}
				if(passengersToUpdate.getLastName() !=null) {
			
		}
				if(passengersToUpdate.getPhoneNumber() !=null) {
			
		}
				if(passengersToUpdate.getEmailAddress() !=null) {
			
		}
				if(passengersToUpdate.getAddressLines() !=null) {
			
		}
				if(passengersToUpdate.getCity() !=null) {
			
		}
				if(passengersToUpdate.getStatProvinceCountry() !=null) {
			
		}
				if(passengersToUpdate.getCountry() !=null) {
			
		}
				if(passengersToUpdate.getOtherPassengerDetails() !=null) {
			
		}
				return passengersRepository.save(passengers);
	}

	@Override
	public Boolean exist(Passengers passengers) {
						return passengersRepository.existsById(passengers.getPassengerId());
																																													}

	@Override
	public List<Passengers> findAll() {
		return passengersRepository.findAll();
	}

}
