/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Passengers;
import java.util.List;

public interface PassengersService {

	public Passengers getOne(Integer passengerId);

	public List<Passengers> findAll();

	public Boolean delete(Integer passengerId);

	public Passengers create(Passengers passengers);

	public Passengers update(Passengers passengers);

	public Boolean exist(Passengers passengers);
}
