/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Payments;
import com.ifi.repository.PaymentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class PaymentsServiceImpl implements PaymentsService {

	@Autowired
	private PaymentsRepository paymentsRepository;

	@Override
	public Payments getOne(Integer paymentId) {
		return paymentsRepository.getOne(paymentId);
	}

	@Override
	public Boolean delete(Integer paymentId) {
		if (paymentsRepository.getOne(paymentId) != null) {
			paymentsRepository.deleteById(paymentId);
			return true;
		}
		return false;
	}

	@Override
	public Payments create(Payments payments) {
		return paymentsRepository.save(payments);
	}

	@Override
	public Payments update(Payments paymentsToUpdate) {
						Payments payments = paymentsRepository.getOne(paymentsToUpdate.getPaymentId());
																		
				if(paymentsToUpdate.getPaymentStatusCode() !=null) {
			
		}
				if(paymentsToUpdate.getPaymentDate() !=null) {
			
		}
				if(paymentsToUpdate.getPaymentAmount() !=null) {
			
		}
				return paymentsRepository.save(payments);
	}

	@Override
	public Boolean exist(Payments payments) {
						return paymentsRepository.existsById(payments.getPaymentId());
																	}

	@Override
	public List<Payments> findAll() {
		return paymentsRepository.findAll();
	}

}
