/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Payments;
import java.util.List;

public interface PaymentsService {

	public Payments getOne(Integer paymentId);

	public List<Payments> findAll();

	public Boolean delete(Integer paymentId);

	public Payments create(Payments payments);

	public Payments update(Payments payments);

	public Boolean exist(Payments payments);
}
