/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;




import java.sql.Date;
import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.RefCalendar;
import com.ifi.repository.RefCalendarRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RefCalendarServiceImpl implements RefCalendarService {

	@Autowired
	private RefCalendarRepository refCalendarRepository;

	@Override
	public RefCalendar getOne(Date dayDate) {
		return refCalendarRepository.getOne(dayDate);
	}

	@Override
	public Boolean delete(Date dayDate) {
		if (refCalendarRepository.getOne(dayDate) != null) {
			refCalendarRepository.deleteById(dayDate);
			return true;
		}
		return false;
	}

	@Override
	public RefCalendar create(RefCalendar refCalendar) {
		return refCalendarRepository.save(refCalendar);
	}

	@Override
	public RefCalendar update(RefCalendar refCalendarToUpdate) {
						RefCalendar refCalendar = refCalendarRepository.getOne((Date) refCalendarToUpdate.getDayDate());
														
				if(refCalendarToUpdate.getDayNumber() !=null) {
			
		}
				if(refCalendarToUpdate.getBusinessDayYn() !=null) {
			
		}
				return refCalendarRepository.save(refCalendar);
	}

	@Override
	public Boolean exist(RefCalendar refCalendar) {
						return refCalendarRepository.existsById((Date) refCalendar.getDayDate());
													}

	@Override
	public List<RefCalendar> findAll() {
		return refCalendarRepository.findAll();
	}

}
