/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.RefCalendar;

import java.sql.Date;
import java.util.List;

public interface RefCalendarService {

	public RefCalendar getOne(Date dayDate);

	public List<RefCalendar> findAll();

	public Boolean delete(Date dayDate);

	public RefCalendar create(RefCalendar refCalendar);

	public RefCalendar update(RefCalendar refCalendar);

	public Boolean exist(RefCalendar refCalendar);
}
