/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:02:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.ReservationPayments;
import java.util.List;

public interface ReservationPaymentsService {

	public ReservationPayments getOne(Integer reservationId, Integer paymentId);

	public List<ReservationPayments> findAll();

	public Boolean delete(Integer reservationId, Integer paymentId);

	public ReservationPayments create(ReservationPayments reservationPayments);

	public ReservationPayments update(ReservationPayments reservationPayments);

	public Boolean exist(ReservationPayments reservationPayments);
}
