/*
 * Created on 2018-09-26 ( Date ISO 2018-09-26 - Time 17:17:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;


import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.ifi.entity.ReservationPayments;
import com.ifi.repository.ReservationPaymentsRepository;

@Service
@Transactional
public class ReservationPaymentsServiceImpl implements ReservationPaymentsService {

	@Autowired
	private ReservationPaymentsRepository reservationPaymentsRepository;

	@Override
	public ReservationPayments create(ReservationPayments reservationPayments) {
		return reservationPaymentsRepository.save(reservationPayments);
	}

	@Override
	public List<ReservationPayments> findAll() {
		return reservationPaymentsRepository.findAll();
	}

	@Override
	public ReservationPayments getOne(Integer reservationId, Integer paymentId) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Boolean delete(Integer reservationId, Integer paymentId) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ReservationPayments update(ReservationPayments reservationPayments) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Boolean exist(ReservationPayments reservationPayments) {
		// TODO Auto-generated method stub
		return null;
	}

}
